- package.json
This PR updates redux npm dependency to 2.0.0.
> Updated redux package version

- examples/counter/package.json
- examples/counter/server.js
- examples/counter/webpack.config.js
Remove all the things you didn't need from the copy & paste.
No more hot loading (that is react) and put the right stuff in the package.json
> Tune package.json and remove hot loading

- examples/counter/containers/App.ts
There is more cleaning I could do but I won't do it until this gets updated to .37
Also I updated the mapping names to match the latest convention we created for this lib.
> Clean App.ts

- examples/counter/components/Counter.ts
Still the events needs to change, but this is not .37 yet.
> Clean Counter.ts

- README.md
> Example of Actions and Angular 2 Dependency Injection

- README.md
> Added an example of angular DI with middlewares

- examples/counter/typings.json
- typings.json
Removes deprecation warnings, old redux typings.
Fixes #58
> Upate typings files

- README.md
per feedback from @TobiasKrogh
> Clarified the connect and select examples in the README

- examples/counter/package.json
- package.json
Also added self to contributors.
> Updated to Angular 2 beta 17 and typescript 1.8.10

- README.md
* Change remaining `import ... from 'angular2/'` to `import ... from '@angular/'`
> docs(*): Update examples to import from '@angular'

- examples/counter/webpack.dev.config.js
* Update webpack.dev.js to alias @angular2/core to allow local dev
> fix(example): Fix local dev mode

- .babelrc
- examples/counter/components/Counter.ts
- examples/counter/components/CounterInfo.ts
- examples/counter/containers/App.ts
- examples/counter/index.ts
- src/___tests___/components/ng-redux.spec.ts
- src/components/dispatch.ts
- src/components/dispatchAll.ts
- src/components/ng-redux.ts
- src/components/select.ts
- src/index.ts
> feat(decorators): select, dispatch, dispatchAll

- src/components/ng-redux.ts
* Instead of importing all of lodash, only import methods we need
> chore(ngRedux): Change lodash imports

- README.md
- examples/counter/components/Counter.ts
- examples/counter/components/CounterInfo.ts
- package.json
- Some copy editing
- Line breaks at 80 chars to make diffs easier going forward
- Updated DI-actions example to use `@dispatch`
- Added @kosz as a contributor.
> Documentation updates

- README.md
> Added npm downloads shield.

- examples/counter/reducers/route.ts
- package.json
- src/___tests___/utils/invariant.spec.ts
- src/components/ng-redux.ts
- src/utils/invariant.ts
- typings.json
> Remove invariant as a dependency

- README.md
- examples/counter/reducers/counter.ts
- examples/counter/reducers/index.ts
- Added some introductory rationale - why should people use this library?
- Added a example of using types to manage complexity in a multi-reducer application.
> Documentation revisions

- package.json
As well as peerDeps - this is for the dev build flow.
> We also need typings in devDeps

- README.md
This is a small documentation fix.
> doc: Fix where constant variable is reassigned

- CHANGELOG.md
- package.json
* 3.3.0
* Features
* DevToolsExtension - convience wrapper for dev tools (#115)
* Select - seamless support for ImmutableJS (#160)
* Fixes
* Able to use `@select` in services
* Behavior of `select` with chained dispatches, (fixes #149, #153)
> v3.3.0 Release

- src/components/dev-tools.ts
> Argument to devtools enhancer should be optional.

- README.md
Use proposed bootstrapModule instead of using to-be-deprecated bootstrap method.
> Update to use proposed bootstrapModule instead.

- README.md
- docs/di-middleware.md
- docs/epics.md
- docs/redux-dev-tools.md
- examples/counter/app/app.component.ts
- examples/counter/app/app.module.ts
- examples/counter/package.json
- package.json
- src/index.ts
> NgModuleify the lib.

- CHANGELOG.md
- examples/counter/components/counter-info.component.ts
- examples/counter/components/counter.component.ts
- examples/counter/components/search.component.ts
- examples/counter/package.json
- examples/counter/store/index.ts
- package.json
- src/components/ng-redux.module.ts
- src/index.ts
- src/utils/wrap-action-creators.ts
- tsconfig.json
* Start adding support for AoT
* Add dev dependencies for angular compiler
* Update tsconfig to tell ngc to emit metadata
> feat(aot): Support AoT - #223

- examples/counter/app/app.module.ts
> sample project missing DevToolsExtension in providers list

- CHANGELOG.md
- package.json
- src/components/dev-tools.ts
- src/ng-redux.module.ts
> Make NgReduxModule.forRoot() expose providers correctly for AoT.

- package.json
> Pin typescript, ts-node versions

- .gitignore
- package.json
- src/ng-redux.module.ts
Reverts angular-redux/ng2-redux#283
> Revert "Fixes build with ngc 2.3.x"

- CHANGELOG.md
- README.md
- package.json
- src/components/ng-redux.ts
Also made a note of the deprecation in the README file.
Connected to #250.
> Added a deprecation warning when `connect` is called.

- CHANGELOG.md
- README.md
- examples/counter/package.json
- examples/counter/yarn.lock
- package.json
- src/components/ng-redux.spec.ts
- src/components/ng-redux.ts
- src/ng-redux.module.ts
> Remove deprecations

- circle.yml
For speed and consistency.
Connected to #278
> Make CI use Yarn

- src/components/ng-redux.spec.ts
- src/components/ng-redux.ts
Which gets an observable for the root state.
> [Fixes #299] Allow a null first arg to select

- CHANGELOG.md
- docs/api.md
- examples/counter/package.json
- examples/counter/src/app/app.component.html
- examples/counter/src/app/app.component.spec.ts
- examples/counter/src/app/app.module.ts
- examples/counter/src/counter/counter-info.component.html
- examples/counter/src/counter/counter-info.component.ts
- examples/counter/src/counter/counter.component.html
- examples/counter/src/counter/counter.component.ts
- examples/counter/src/search/search.component.html
- examples/counter/src/search/search.component.ts
- examples/counter/src/select-by-path/select-by-path.component.html
- examples/counter/src/select-by-path/select-by-path.component.ts
- examples/counter/src/select-root-state/select-root-state.component.html
- examples/counter/src/select-root-state/select-root-state.component.ts
- package.json
- src/components/ng-redux.ts
> Release prep for 5.1.0

- README.md
URLs should not have @ in them.
> Fixes broken URLs in README

- docs/intro-tutorial.md
> Fixed typos

- docs/intro-tutorial.md
I fixed a few typos found while studying the intro tutorial.
That document has been a great help to me!
> fix few typos in example code

- docs/intro-tutorial.md
> Update docs to reflect new Angular CLI package name

- examples/counter/.angular-cli.json
- examples/counter/package.json
Fixes #342 and updates the counter example to use angular CLI latest version.
> Counter example fix, compatible with angular/cli 1.0.0-rc.1

- docs/intro-tutorial.md
I had some troubles following the tutorial as I missed some lines where changes were made. This pr adds indications to some missing 'new' and 'changed' lines and makes the marking consistent ( <- instead of <-- which was used in some places - using only one of them 😉 )
> Indicating new and changed lines

- articles/quickstart.md
Redux-logger 3.0.0 introduced a breaking change in its exports.
> Update redux-logger import

- articles/intro-tutorial.md
the link to the docs was broken
> fixed "async-pipe" angular docs link

- src/components/root-store.spec.ts
- src/components/sub-store.spec.ts
- src/components/sub-store.ts
- src/decorators/dispatch.spec.ts
- src/decorators/select.spec.ts
- src/decorators/select.ts
- src/decorators/with-sub-store.spec.ts
- src/decorators/with-sub-store.ts
- testing/ng-redux.mock.spec.ts
- testing/ng-redux.mock.ts
- testing/observable-store.mock.ts
- tsconfig.build.json
- tsconfig.docs.json
- tsconfig.json
- tsconfig.testing.json
Adding `"noUnusedLocals": true, "noUnusedParameters": true` caught a bunch of minor stuff.
> Turn tsconfig settings to 11

- articles/intro-tutorial.md
`implements OnDestroy` was missing. Without it, it wouldn't work.
> Docs add interface implementation DisplayingState

- articles/select-pattern.md
Add `@select$` to documentation, closes #486
> [#486] docs: select$ decorator

- package-lock.json
- src/utils/set-in.spec.ts
- src/utils/set-in.ts
Fixing #463 by allowing `setIn` to use the internal `setIn` method of an object if it exists.
> Fixing Fractal Stores issue with ImmutableJS

- testing/ng-redux.mock.ts
> Fixes #508
