angular-redux/store

examples/counter/components/Counter.ts, examples/counter/containers/CounterApp.ts
Just an improvement: To have really a "dump" Counter component it should not have a reference to all actions. The Counter component receives its data as properties as usual, but just the action handler as needed (not all actions).
=> Counter should to be a "dump" component w/o referencing to all Redux actions

examples/counter/package.json, examples/counter/reducers/counter.ts, examples/counter/tsconfig.json
Upgrade to latest TS 1.6 to support "[Default initializers on required parameters](https://github.com/Microsoft/TypeScript/pull/4022)" and [all the sugar](http://blogs.msdn.com/b/typescript/archive/2015/09/16/announcing-typescript-1-6.aspx).
=> Support of TypeScript 1.6

README.md
No longer need to register NgRedux directly as a provider
=> chore(readme) Update bootstrap

README.md, examples/counter/containers/App.ts, examples/counter/package.json, examples/counter/store/configureStore.ts, examples/counter/store/utils.d.ts
This is because they don't require a dependency on React.
Also showed an example of enabling Angular 2 to refresh after events fired by the dev tools.
=> Prefer the chrome extension dev tools in README

README.md
* Update example to dispatch with a type property, related to #71 where
the fact that dispatch should return a JSON object with a type
property wasn't clear.
@SethDavenport
=> docs(readme): Update readme connects #71

src/___tests___/decorators/select.spec.ts, src/decorators/select.ts
ngRedux.select has the ability to pass in a custom compare function,
didn't have this on the `@select` decorator, added this.
```js
let compare = (a,b) => a.x === b.x
class MyComponent() {
@select(state=>state,compare) state$:Obserable<any>;
}
```
=> feat(select): Custom comparer in select decorator

package.json
when including ng2-redux as a dev-dependency in my project, ```npm install``` fails due to 
```
> ng2-redux@2.3.4 postinstall /opt/atlassian/bitbucketci/agent/build/node_modules/ng2-redux
> typings install
sh: 1: typings: not found
```
moving it to peer-dependencies should ensure that typings is installed before ng2-redux's post-install script is run.
=> moved typings to peerDependencies

src/decorators/index.ts, src/index.ts
Relying on folder level `index.ts` files makes systemJS harder to configure. Might as well do the simple thing and be explicit in the one place we were using this pattern.
=> SystemJS friendliness.

examples/counter/actions/counter-actions.ts, src/___tests___/decorators/select.spec.ts, src/components/ng-redux.ts, src/decorators/select.ts
I was playing around with select and ng2-redux, it worked for all use cases, code is very clean, and it looks awesome guys. 
I don't know if this is useful, but since our select method already supports this feature I thought it'd be interesting to have the comparer function as an argument for @select as well.
Comparer function to select a particular property seems useless, at least using with immutable. The default comparer already deals with it even if the same immutable slice gets updated in another sibling (which would generate a new object). 
I wonder if when selecting just the slice might be a good shot. Thoughts?
=> Adding comparer to select decorator.

CHANGELOG.md, package.json
@SethDavenport @danielfigueiredo prepping 3.1 release - version bump + details in changelog 
Since we are adding new features, minor version bump instead of a patch, no breaking changes that I'm aware of.
=> Prepare v3.1.0 release

src/___tests___/components/ng-redux.spec.ts, src/___tests___/decorators/select.spec.ts, src/components/ng-redux.ts
Because it causes an issue with actions that are dispatched from `ngOnInit()`.
This was used to handle updates from the redux devtools extension in earlier betas/release candidates. However it seems that the underlying zone issue has been fixed in RC.3: the devtools appear to work without it.
=> Remove appref.tick() stuff.

README.md, examples/counter/containers/App.ts, examples/counter/store/index.ts, src/components/dev-tools.ts, src/index.ts
RC4 seems to require the use of AppRef.tick() again to propagate store changes from the dev tools extension.
Since doing it directly in NgRedux is problematic, I've created a wrapper component for it that triggers only for external events (not for actions dispatched in the Angular 2 zone.
This wrapper also neatly hides some of the messiness of accessing `window.devToolsExtension` in TypeScript.
=> Convenience wrapper for the dev tools extension.

CHANGELOG.md, README.md, docs/action-creator-service.md, docs/api.md, docs/connect-pattern.md, docs/di-middleware.md, docs/epics.md, docs/immutable-js.md, docs/redux-dev-tools.md, docs/select-pattern.md
Having everything in README.md was getting a bit hard to maintain, so I split up the sections into their own markdown files. I also added some more material:
- A write up on using ImmutableJS + Ng2Redux
- A resources section with links to talks, general redux community stuff, and the Redux/Ngrx section of the ngcourse2 book from Rangle.io.
I also rejigged the README ordering a bit in an attempt to make it more friendly to newcomers.
=> Beefing up docs, re-org

src/utils/get-in.ts
Instead of using an 'optional' require() statement inside of a try-catch, just look for a 'getIn' function on the data structure passed to getIn(), and if it exists, use it. This eliminates a big nasty Webpack warning.
Fixes #165
=> Change immutablejs integration approach

.npmignore
Suppresses some warnings from angular-cli@webpack
May also fix #64.
=> [Fixes #180] Include source files in npm

src/components/dev-tools.ts
DevTools component throws "ReferenceError: window is not defined" when run on node using Universal. This happens even if you are not including the dev tools enhancer; by virtue of the component being imported in index.ts, the (generated) line below is executed but fails when run in node:
var environment = window || this;
Just added an explicit typeof check around window
=> Bug fix for #172

examples/counter/package.json, package.json
Angular itself lists a dependency of ^0.6.5, so we shouldn't be restricting it further.
=> [Fixes #187] Relax zonejs version.

package.json, src/components/dev-tools.ts
Occasionaly events sent from DevTools will be outside of the Angular
zone and changes won't get reflected. When dev tools start - subscribe
to the store, if not in angular zone - cause a tick for changes to get
reflected.
=> fix dev tools out of sync

CHANGELOG.md, package.json
The chai type def has this...
```
interface Object {
should: Chai.Assertion;
}
```
When we run build, on files that have things like:
`let x = (y:Object):Obect => { }`
In the resulting file.d.ts
```
/// <reference types="chai" />
```
Gets added, causing things to blow up for people. Not good.
Temp fix for now - when running build, uninstall the types - then
re-install them after.
Not happy with this, but rather this than having a patch causing
breaking builds for using 3.3.8.
=> fix(build): No chai for you

docs/select-pattern.md
Binding brackets in angular 2 should be {{binding}} not {binding} as in the example code
=> @select example code snippet is missing brackets

README.md
The API link goes to `#api` instead of `docs/api.md`.
=> Documentation API Link Fix

.gitignore, package.json, src/ng-redux.module.ts
It seems the whole complexity with `NgReduxModule.forRoot()` is not necessary. Refactoring this to a simple providers array seems to fix the build problems in #282.
=> Fixes build with ngc 2.3.x

docs/epics.md
Without this, the operator won't be defined. Which is prolly why when @jcperez-ch tried to use `flatMap` (which is *still* a supported alias of `mergeMap`) it wasn't there--you have to import `mergeMap` to get the `flatMap` alias.
=> docs(epics): import mergeMap operator patch

docs/intro-tutorial.md
Missing type `<IAppState>` from the ngRedux property in the AppComponent constructor.
=> Update ngRedux on AppComponent

docs/intro-tutorial.md
Following the intro tutorial I ran into a line containing the .ts file extension in an import statement.
=> Fix typo in import statement. Delete .ts extension

src/components/ng-redux.ts
This is important for middlewares like redux-thunk that allow you to dispatch other things than Actions.
[Fixes #264] [Fixes #386] [Fixes #211]
=> Fix typings for dispatch method

src/components/ng-redux.ts, src/decorators/select.spec.ts, src/decorators/select.ts, src/index.ts
`@select$` is a version of `@select` that lets you attach a chain of RXJS operations directly in your decorator. So instead of doing
```typescript
class Foo {
readonly debouncedFooBar$: Observable<string>;
constructor(ngRedux: NgRedux) {
this.debouncedFooBar$ = ngRedux.select('foo')
.map(foo => foo.bar)
.debounce(300);
}
}
```
or
```typescript
class Foo {
readonly @select() foo$: Observable<IFoo>;
readonly debouncedFooBar$: Observable<string>
constructor() {
this.debouncedFooBar$ = this.foo$
.map(foo => foo.bar)
.debounce(300);
}
}
```
You can instead do
```typescript
export const getBarAndDebounce = obs$ => obs$
.map(foo => foo.bar)
.debounce(300);
class Foo {
readonly debouncedFooBar$: Observable<string> = @select$(getBarAndDebounce);
}
```
=> [Fixes #269] Adds `@select$` decorator

src/decorators/select.spec.ts, src/decorators/select.ts
Because this: `@select$(veryComplexTransformer)` would be inefficient because the disctinctUntilChanged happens after `veryComplexTransformer` runs, on every store update.
Being able to use `@select$(['path', 'to', 'something'], veryComplexTransformer)`  will only run `veryComplexTransformer` when `store.path.to.someting` changes, which is better.
=> Added selector parameter to @select$ after all

testing/ng-redux-testing.module.ts
The unused `ClassProvider` import in the testing module is throwing errors when the `noUnusedLocals` option is turned on in `tsconfig.json`.
=> Remove unused testing module import

package.json, src/components/ng-redux.ts
Redux-batch (`@manaflair/redux-batch`) works by overriding Redux's subscribe and notify mechanism. However, the way we were creating an observable out of the store was pushing updates independently of `store.subscribe()`. This has the effect that `observable.next()` was being called independently of redux-batch's patched subscribe/notify mechanism and selectors fire on each change of the batched action set.
The fix is to re-create our observable in terms of store.subscribe() in order to catch any adjustments made by 3rd-party enhancers.
=> [Fixes #372] Add support for redux-batch

package.json, src/decorators/dispatch.spec.ts, src/decorators/dispatch.ts, src/decorators/select.spec.ts, src/index.ts, tsconfig.build.json, yarn.lock
Initial implementation of a `@dispatch` decorator.
```ts
class TestClass {
instanceProperty = 'test'
@dispatch()
myMethod(value) {
return {
type: 'TEST',
payload: {
value,
instanceProperty: this.instanceProperty
}
}
}
}
```
Need to do some integration testing, and ensure that the context of `this` is preserved as expected if action creators are using it.
Feature was requested in #384 - needs some more testing, code cleanup, better typings, etc.
=> feat(dispatch): Create dispatch decorator

src/components/ng-redux.ts, src/components/selectors.spec.ts, src/components/selectors.ts, src/decorators/select.ts, src/index.ts, src/utils/assert.ts, testing/ng-redux.mock.ts
* Splits out selector logic into its own file and simplifies it.
* Adds unit tests for that selector logic.
* Reworks a lot of the code in a more functional style.
* Simplifies the workaround for n-arity compose in TypeScript.
=> Code cleanup

.npmignore, CHANGELOG.md, package.json, src/components/ng-redux.ts, src/components/observable-store.ts, src/components/selectors.ts, src/components/sub-store.ts, src/decorators/select.spec.ts, src/decorators/select.ts, src/index.ts, src/utils/selection-map.ts, testing/ng-redux.mock.ts
`@select` and `@select$` cache the results of their selections, in order to avoid memory leaks. However we need to be able to reset these cached copies when MockNgRedux.reset() is called. The solution is to track the cached selections in a lookup table instead of as closure variables in the decorator itself.
=> [Fixes #413] allow tests to reset observables cached by decorators

CHANGELOG.md, package.json, testing/ng-redux.mock.ts
=> Reset `MockNgRedux.mockInstance` as part of `MockNgRedux.reset`.

testing/package.json
Added a package.json file in the testing directory so that imports to `@angular-redux/store/testing` resolve to the compiled files under `lib/testing` instead of the source ones.
This allows TypeScript users to compile tests while referencing the proper `.d.ts` file, which avoids issues when an app uses different compiler flags than this library.
Should also allow JS users using a transpiler like babel to use the `testing` module.
=> [Fix #415] Use compiled files when importing the testing module

package.json, src/components/ng-redux.ts, src/components/root-store.spec.ts, src/components/root-store.ts, src/components/sub-store.spec.ts, src/decorators/dispatch.spec.ts, src/decorators/select.spec.ts, src/ng-redux.module.ts, testing/ng-redux-testing.module.ts, testing/ng-redux.mock.ts, testing/observable-store.mock.ts
1) Reorganize interfaces internally to make sure MockNgRedux and NgRedux are structurally compatible (issue #419)
2) Fix a boundary condition where two instances of MockNgRedux could be created in certain cases.
=> Testing module fixes

CHANGELOG.md, package.json, src/components/selectors.ts, src/components/sub-store.spec.ts, src/decorators/with-sub-store.spec.ts
Calling `.select` with PropertySelector would throw an exception in this case; however it
should return an observable with an initial value of undefined instead.
=> Fixed a bug where subStores had issues with nonexistent base paths.

CHANGELOG.md, package.json, src/components/root-store.ts
When creating an observable of the store, make sure the new observable closes down the resources it's using.
This particular leak was introduced in 6.3.0.
=> [Fixes #427] Memory Leak in .select

src/components/root-store.ts
the app explodes if devTools are disabled because "ApplicationRef._tick called recursively"
and NgRedux dispatch is in the stack, as well as two NgZone.run calls
basically it's
* ApplicationRef._tick -> ngOnInit -> subscribe -> bunch of rxjs internals -> ngRedux.dispatch -> ngZone.run -> ApplicationRef._tick
fix: check if in ngZone and only do `this.ngZone.run( .... )` if not
=> fix recursive app tick

CHANGELOG.md, README.md
Use `@angular-redux/store@^7` - this version supports Angular 5, and also changes to using lettable operators.
Any new major releases will released on the v7 branch and with the `@latest` tag for final publishes.
Use `@angular-redux/store@^6` - This supports Angular 4 and earlier.
Where possible, I will be maintaining and applying any fixes / enhancements for v7 into v6 where it does not introduce a breaking change.
I made a few mistakes trying to publish fixes / etc to two major versions, which caused some releases to get tagged incorrectly and caused some confusion. Sorry for any confusion this has caused, and will do better on avoiding this in the future, and being more transparent with the releases that are going out.
=> Clarify Versioning

src/components/ng-redux.ts, src/decorators/dispatch.spec.ts, src/decorators/dispatch.ts
Adding a way for methods that use the `@dispatch` decorator to return a value that won't trigger a dispatch so they can conditionally dispatch based on any logic that suits the need. 
Currently returning anything but an action would cause middleware like redux-observable to throw or returning a mock action like `{ type: 'noop' }` would still activate the root reducer that, even though technically nothing will happen, just seems nicer that you can avoid all together the store.dispatch from within the same @dispatch-decorated method.
By having a specific value to allow this behaviour — rather than just using null or undefined — prevents accidental development errors of developers just forgetting to return.
=> Adding a way for @dispatch methods to return a value that won't trigger a dispatch

src/components/selectors.ts, src/decorators/helpers.ts
This will allow to access any other property of component inside of transformation function, e.g:
```
@Input() public anotherInput: string;
@select$(['selector'], (obs$, inst) => obs$.filter(x => x.name === inst.anotherInput))
public selectedObs: Observable<any>;
```
Such changes, IMHO, is pretty easy and it has backward compatibility.
=> Add possibility to access component scope inside of 'transformer' function
